---

- name: Loops playbook
  hosts: all
  become: yes

  tasks:
          - name: Say Hello to All
            debug: msg='hello {{ item }}'
            loop: 
               - 'bob'
               - 'nick'
               - 'pop'

          - name: loop example
            shell: echo -n Z >> myfile.txt &&cat myfile.txt
            register: output
            delay: 2
            retries: 10
            until: output.stdout.find('ZZZZ') == false

          - name: print final output
            debug:
                    var: output.stdout

          - name: install some
            apt: name={{ item }} state=latest
            loop:
                    - tree
                    - mc

