---
- name: Install apache2
  hosts: all
  become: yes

  tasks:
          - name: Install apache2
            apt: name=apache2 state=latest

          - name: Start apache
            service: name=apache2 state=started enabled=yes
