---
- name: Install apache and index.html
  hosts: apache_test
  become: True
  tasks:
        - name: Install Apache
          apt:
              name:
                  apache2
                  state:
                      present

        - name: Start apache and make it enable
          service:
              name:
                  apache2
                  state:
                      started
                      enabled:
                          True

        - name: Copy
          copy:
              src: index.html
              dest: /var/www/html/
