---
- name: Install apache and index.html
  hosts: apache_test
  become: yes
  tasks:
        - name: Install Apache
          apt: name=apache2 state=latest

        - name: Start apache and make it enable
          service: name=apache2 state=started enabled=yes

        - name: Copy
          copy: src=index.html dest=/var/www/html/ mode=0555
