---
- name: Install apache and index.html
  hosts: all
  become: yes

  vars:
          source_file: ./mysite/index.html
          destin_file: /var/www/html

  tasks:
        - name: Check linux version
          debug: var=ansible_os_family
        
        - block: #========Debian===========

            - name: Install Apache
              apt: name=apache2 state=latest
          
            - name: Copy home page to servers
              copy: src={{ source_file }} dest={{ destin_file }} mode=0555
              notify: Restart apache                                      

            - name: Start apache and make it enable
              service: name=apache2 state=started enabled=yes          

          when: ansible_os_family == 'Debian'  
 
        - block: #=========RedHat============

            - name: Install Apache
              yum: name=httpd state=latest

            - name: Copy home page to servers
              copy: src={{ source_file }} dest={{ destin_file }} mode=0555
              notify: Restart apache
          
            - name: Start apache and make it enable on boot RedHat
              service: name=httpd state=started enabled=yes
          
          when: ansible_os_family == 'RedHat'

  handlers:
        - name: Restart apache
          service: name=apache2 state=restarted  
                                        
        - name: Restart apache
          service: name=httpd state=restarted 
